# Site settings
title: "artikblue"
bye_message: "Thx!"
baseurl: "/"
url: "https://artikblue.github.io"
disqus: artikblue

# Header settings
nick: "artikblue"
mail:
    domain: "protonmail"
    ext: "com"
source_code:
    server: "github.com"
    nick: "artikblue"
blog:
    server: "github.io"
    nick: "artikblue"
fingerprint_key: "AB17 8757 1394 4322 3E0C  A929 F208 556C 02FD BE3A"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
